kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: dev-cluster1
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30002
        hostPort: 30002
        protocol: TCP
  - role: worker
  - role: worker