spring:
    application:
        name: wclient
    cloud:
      discovery:
        enabled: true
server:
    port: 8032

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8033/eureka


